### PR TITLE
Return more informations about modules + add PHP 8 compatibility

### PR DESCRIPTION
**Pull request by atomiix**

### CODE REVIEW

**Review by mickaelandrieu — APPROVED** [review]
Thank you @atomiix !

**Comment by PierreRambaud** [comment]
> TBH I didn't know this package was still used : you may consider to fork it as I don't maintain it at all since I'm not part of PS Core team anymore.
> 
> Have a nice day

Hey, instead of forking, maybe you can transfer ownership to the PrestaShop organization? wdyt?

**Comment by mickaelandrieu** [comment]
Hi @PierreRambaud,

Yes I think it's a good idea as your team is probably the only user of this package.

I will give your the proper rights to do it.

Regards.

**Comment by PierreRambaud** [comment]
> Hi @PierreRambaud,
> 
> Yes I think it's a good idea as your team is probably the only user of this package.
> 
> I will give your the proper rights to do it.
> 
> Regards.
> 
> PS : Let me know if you change the organization name because I'll need to declare this package abandoned on packagist. PS2: check your GitHub notifications slightly_smiling_face

Thanks, I'll do it today :pray:

**Comment by PierreRambaud** [comment]
> Hi @PierreRambaud,
> 
> Yes I think it's a good idea as your team is probably the only user of this package.
> 
> I will give your the proper rights to do it.
> 
> Regards.
> 
> PS : Let me know if you change the organization name because I'll need to declare this package abandoned on packagist. PS2: check your GitHub notifications slightly_smiling_face

I transfer the ownership of this repository. You're now able to mark the package as abandoned. We will change the organization name in packagist as soon as possible.
Thanks again :pray:

**Pull request merged**
